hal/uart_ll.h: Fix compile with C++ deprecated volatile use
These headers no longer work in C++ code with newer versions of GCC:

esp-idf/components/hal/esp32c6/include/hal/uart_ll.h: In function 'void uart_ll_ena_intr_mask(uart_dev_t*, uint32_t)':
esp-idf/components/hal/esp32c6/include/hal/uart_ll.h:229:21: error: compound assignment with 'volatile'-qualified left operand is deprecated [-Werror=volatile]
  229 |     hw->int_ena.val |= mask;
      |     ~~~~~~~~~~~~~~~~^~~~~~~
esp-idf/components/hal/esp32c6/include/hal/uart_ll.h: In function 'void uart_ll_disable_intr_mask(uart_dev_t*, uint32_t)':
esp-idf/components/hal/esp32c6/include/hal/uart_ll.h:242:21: error: compound assignment with 'volatile'-qualified left operand is deprecated [-Werror=volatile]
  242 |     hw->int_ena.val &= (~mask);
      |     ~~~~~~~~~~~~~~~~^~~~~~~~~~