undefined reference to `bootloader_flash_update_size'
undefined reference to `bootloader_flash_update_size'
ESP32-S3 was missing bootloader_flash_update_size