hal/uart_ll.h: Fix compile with C++
I'm including <hal/uart_ll.h> in my C++ application because I need to
bypass the uart driver. The inline functions in the header file fail to
compile as C++.

With xtensa-esp32s2-elf-g++ (crosstool-NG esp-2021r2-patch3) 8.4.0 it
doesn't allow copying the union like this:

hal/uart_ll.h:131:39: error: binding reference of type 'const uart_dev_s::<unnamed union>&' to 'volatile uart_dev_s::<unnamed union>' discards qualifiers
     typeof(hw->clk_div) div_reg = hw->clk_div;
hal/uart_ll.h:131:39: error: cannot bind rvalue reference of type 'uart_dev_s::<unnamed union>&&' to lvalue of type 'volatile uart_dev_s::<unnamed union>'
     typeof(hw->clk_div) div_reg = hw->clk_div;

All of the enums need explicit casts for conversion to/from integers.