Fixed type of `drom_start_addr` due to following compiler complain:
```
error: comparison of integer expressions of different signedness: 'intptr_t' {aka 'int'} and 'uint32_t' {aka 'long unsigned int'} [-Werror=sign-compare]
  286 |     return ((intptr_t)p >= drom_start_addr && (intptr_t)p < SOC_DROM_HIGH);
      |             ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```